Repository ilios/ilios, pull requests merged in 2018-02, with the labels that each got.

#2048 Squish deprecation warnings
  src/Ilios/CliBundle/Command/AuditLogExportCommand.php
  tests/AuthenticationBundle/Classes/SessionUserTest.php
  tests/CliBundle/Command/AuditLogExportCommandTest.php
Labels: Ready for Review

#2049 Update Dependencies
  composer.lock
Labels: Ready for Review, in progress

#2050 Allow courses to be linked to new cohorts when rolling over
  src/Ilios/CoreBundle/Entity/Manager/CohortManager.php
  src/Ilios/CoreBundle/Resources/config/services.yml
  src/Ilios/CoreBundle/Resources/config/virtual-managers.yml
  src/Ilios/CoreBundle/Service/CourseRollover.php
  tests/CoreBundle/Service/CourseRolloverTest.php
Labels: Ready for Review, in progress

#2052 Update Dependencies
  composer.lock
Labels: Ready for Review, in progress

#2057 Dockerfile now working with http only
  Dockerfile
Labels: in progress

#2054 Filter objectives by fullCourses
  src/Ilios/CoreBundle/Entity/Repository/ObjectiveRepository.php
  tests/IliosApiBundle/Endpoints/ObjectiveTest.php
Labels: Ready for Review, in progress

#2058 Cleanup composer cache when building
  Dockerfile
Labels: Ready for Review, in progress

#2059 Update docker compose for development with new container setup
  docker-compose.yml
Labels: Ready for Review, in progress

#2053 Add cohort rollover option to course rollover endpoint
  app/config/config.yml
  src/Ilios/ApiBundle/Controller/CoursesController.php
  src/Ilios/CoreBundle/Service/CourseRollover.php
  tests/CoreBundle/DataLoader/CohortData.php
  tests/CoreBundle/DataLoader/ObjectiveData.php
  tests/CoreBundle/DataLoader/ProgramData.php
  tests/CoreBundle/DataLoader/ProgramYearData.php
  tests/IliosApiBundle/Endpoints/CohortTest.php
  tests/IliosApiBundle/Endpoints/CourseTest.php
  tests/IliosApiBundle/Endpoints/ObjectiveTest.php
  tests/IliosApiBundle/Endpoints/ProgramYearTest.php
Labels: Ready for Review, in progress

#2060 Read ENV variables from $_ENV as well as $_SERVER
  src/Ilios/CoreBundle/Service/Config.php
  tests/CoreBundle/Service/ConfigTest.php
Labels: Ready for Review, in progress

#2064 new permissions system: only root users can delete schools.
  src/Ilios/AuthenticationBundle/Classes/Capabilities.php
  src/Ilios/AuthenticationBundle/RelationshipVoter/School.php
  src/Ilios/AuthenticationBundle/Service/DefaultPermissionMatrix.php
  src/Ilios/AuthenticationBundle/Service/PermissionChecker.php
  tests/AuthenticationBundle/RelationshipVoter/SchoolTest.php
Labels: Ready for Review, in progress

#2063 allow for target/_blank attr/value on anchor tags.
  app/config/config.yml
  tests/IliosApiBundle/Endpoints/ObjectiveTest.php
Labels: Ready for Review, in progress
