Repository ilios/ilios, pull requests merged in 2018-06, with the labels that each got.

#2172 make Curriculum Inventory exporter testable
  src/Ilios/CoreBundle/Entity/Repository/CurriculumInventoryReportRepository.php
  src/Ilios/CoreBundle/Service/CurriculumInventory/Export/Aggregator.php
  src/Ilios/CoreBundle/Service/CurriculumInventory/Export/XmlPrinter.php
  src/Ilios/CoreBundle/Service/CurriculumInventory/Exporter.php
  tests/CoreBundle/Service/CurriculumInventory/ExporterTest.php
Labels: Code Quality, Enhancement

#2175 Bump the API version to 1.31
  app/config/config.yml
Labels: Ready for Review

#2174 add session/course objectives and related competencies to calendar-events
  src/Ilios/ApiBundle/Controller/SchooleventController.php
  src/Ilios/ApiBundle/Controller/UsereventController.php
  src/Ilios/CoreBundle/Classes/CalendarEvent.php
  src/Ilios/CoreBundle/Entity/Manager/SchoolManager.php
  src/Ilios/CoreBundle/Entity/Manager/UserManager.php
  src/Ilios/CoreBundle/Entity/Repository/SchoolRepository.php
  src/Ilios/CoreBundle/Entity/Repository/UserRepository.php
  src/Ilios/CoreBundle/Traits/CalendarEventRepository.php
  tests/CoreBundle/DataLoader/CompetencyData.php
  tests/CoreBundle/DataLoader/ObjectiveData.php
  tests/CoreBundle/DataLoader/SessionData.php
  tests/IliosApiBundle/Endpoints/ObjectiveTest.php
  tests/IliosApiBundle/Endpoints/SchooleventsTest.php
Labels: Ready for Review

#2176 Update Dependencies
  composer.lock
Labels: in progress

#2180 Split up lines in tests
  .travis.yml
  src/Ilios/CoreBundle/Service/CurriculumInventory/Export/XmlPrinter.php
Labels: Ready for Review, in progress

#2182 Update Dependencies
  composer.lock
Labels: Ready for Review, in progress

#2185 Update Dependencies
  composer.lock
Labels: Ready for Review, in progress

#2179 Cleanup orphaned objectives onFlush
  app/Resources/DoctrineMigrations/Version20180617000000.php
  src/Ilios/CoreBundle/Entity/Objective.php
  src/Ilios/CoreBundle/Entity/ObjectiveInterface.php
  src/Ilios/CoreBundle/EventListener/RemoveOrphanedObjectives.php
  src/Ilios/CoreBundle/Resources/config/services.yml
  tests/CoreBundle/Entity/ObjectiveTest.php
  tests/IliosApiBundle/Endpoints/CourseTest.php
  tests/IliosApiBundle/Endpoints/ObjectiveTest.php
  tests/IliosApiBundle/Endpoints/ProgramYearTest.php
  tests/IliosApiBundle/Endpoints/SessionTest.php
Labels: Ready for Review, in progress

#2187 Non-learners get materials from draft events
  src/Ilios/CoreBundle/Entity/Repository/UserRepository.php
  src/Ilios/CoreBundle/Traits/CalendarEventRepository.php
  tests/IliosApiBundle/Endpoints/SchooleventsTest.php
  tests/IliosApiBundle/Endpoints/UsereventTest.php
Labels: Ready for Review, in progress
