Repository ilios/ilios, pull requests merged in 2018-09, with the labels that each got.

#2218 Update Dependencies
  composer.lock
Labels: Ready for Review, in progress

#2225 Adding ENV var documentation
  docs/env_vars_and_config.md
Labels: in progress

#2226 fixed SetEnvIf syntax for ILIOS_SECRET, added 'remove' alongside 'deprecate/ing'
  docs/env_vars_and_config.md
Labels: in progress

#2227 Update Dependencies
  composer.json
  composer.lock
Labels: Ready for Review, in progress

#2231 Replace parameters with ENV variables
  .travis.yml
  Dockerfile
  app/Resources/DoctrineMigrations/Version20170824000000.php
  app/config/config.yml
  app/config/config_dev.yml
  app/config/config_prod.yml
  app/config/config_test.yml
  app/config/parameters.yml.dist
  app/config/parameters.yml.travis
  composer.json
  composer.lock
  docker-compose.yml
  docs/env_vars_and_config.md
  docs/update.md
  src/AppBundle/Composer/CheckRequiredENV.php
Labels: Ready for Review

#2232 Update Dependencies
  composer.lock
Labels: Ready for Review, ready

#2235 Use the container and client from our test bundle
  tests/AppBundle/AbstractEndpointTest.php
  tests/AppBundle/DataFixtures/ORM/AbstractDataFixtureTest.php
  tests/AppBundle/Endpoints/AcademicYearTest.php
  tests/AppBundle/Endpoints/AuthenticationTest.php
  tests/AppBundle/Endpoints/CohortTest.php
  tests/AppBundle/Endpoints/CourseTest.php
  tests/AppBundle/Endpoints/CurrentSessionTest.php
  tests/AppBundle/Endpoints/CurriculumInventoryInstitutionTest.php
  tests/AppBundle/Endpoints/CurriculumInventorySequenceTest.php
  tests/AppBundle/Endpoints/IlmSessionTest.php
  tests/AppBundle/Endpoints/ObjectiveTest.php
  tests/AppBundle/Endpoints/OfferingTest.php
  tests/AppBundle/Endpoints/ProgramYearStewardTest.php
  tests/AppBundle/Endpoints/ProgramYearTest.php
  tests/AppBundle/Endpoints/SchooleventsTest.php
  tests/AppBundle/Endpoints/SessionDescriptionTest.php
  tests/AppBundle/Endpoints/SessionTest.php
  tests/AppBundle/Endpoints/SessionTypeTest.php
  tests/AppBundle/Endpoints/UsereventTest.php
Labels: Ready for Review, in progress

#2234 Update test dependencies
  app/config/config_test.yml
  composer.json
  composer.lock
Labels: Ready for Review, in progress

#2233 Remove deprecated Symfony RoleInterface
  src/AppBundle/Entity/UserRole.php
  src/AppBundle/Entity/UserRoleInterface.php
  tests/AppBundle/Entity/UserRoleTest.php
Labels: Ready for Review, in progress

#2236 Remove unused dependencies
  app/AppKernel.php
  composer.json
  composer.lock
Labels: Ready for Review, ready

#2241 Add a bunch of health checks
  composer.json
  config/packages/monitor.yaml
  config/services.yaml
  src/Composer/CheckRequiredENV.php
  src/Monitor/Frontend.php
  src/Monitor/IliosFileSystem.php
  src/Monitor/PhpConfiguration.php
  src/Monitor/RequiredENV.php
  src/Monitor/Timezone.php
Labels: Ready for Review, ready

#2242 Use the builtin symfony cache
  config/packages/framework.yaml
  config/packages/prod/doctrine.yaml
  config/packages/prod/framework.yaml
  config/services.yaml
  src/Service/CacheFactory.php
  tests/Service/CacheFactoryTest.php
Labels: Ready for Review, ready

#2240 Replace with packs
  composer.json
  composer.lock
  config/bundles.php
  config/packages/dev/debug.yaml
  symfony.lock
Labels: Ready for Review, ready

#2238 Re-organize the .env.dist file
  .env.dist
Labels: Ready for Review, ready

#2239 Fix docker path to webroot
  Dockerfile
  docker/apache.conf
Labels: Ready for Review, ready

#2244 Fix Session Timestamp test
  tests/Endpoints/SessionTest.php
Labels: Ready for Review, in progress

#2248 Setup ENV variables for PHP
  Dockerfile
  src/Monitor/PhpConfiguration.php
Labels: Ready for Review, in progress

#2247 Fix local development container
  docker-compose.yml
Labels: Ready for Review, in progress

#2246 Update the front controller to match the recipe
  public/index.php
Labels: Ready for Review, in progress

#2249 Modify the way we generate update timestamp
  src/Service/Timestamper.php
  tests/AbstractEndpointTest.php
Labels: ready

#2251 Docker Cleanup
  Dockerfile
  docker/apache.conf
  docker/ilios.ini
  docker/monolog.yaml
  docker/php.ini
Labels: Ready for Review, ready

#2243 Update Dependencies
  composer.json
  composer.lock
Labels: Ready for Review, in progress

#2250 Default Ilios to production
  .env.dist
  .travis.yml
  bin/console
  public/index.php
  src/Monitor/RequiredENV.php
Labels: Ready for Review, ready

#2252 Add a setup script
  bin/setup
  composer.json
  docs/install.md
  docs/update.md
Labels: Ready for Review, ready

#2255 Re-organize the index.html template to load faster
  src/Controller/IndexController.php
  templates/index/webindex.html.twig
Labels: Ready for Review, ready

#2256 Enable the http2 module
  Dockerfile
Labels: Ready for Review, ready

#2258 allow null value for parent setter arg.
  src/Entity/CurriculumInventorySequenceBlock.php
  src/Entity/CurriculumInventorySequenceBlockInterface.php
  tests/Endpoints/CurriculumInventorySequenceBlockTest.php
Labels: ready
