Repository ilios/ilios, pull requests merged in 2018-12, with the labels that each got.

#2290 Update Dependencies
  composer.json
  composer.lock
  config/packages/translation.yaml
  src/Controller/ApiController.php
  src/Controller/BadRequestController.php
  src/Controller/ConfigController.php
  src/Controller/DirectoryController.php
  src/Controller/ErrorController.php
  src/Controller/IcsController.php
  src/Controller/IndexController.php
  src/Controller/SchooleventController.php
  src/Entity/User.php
  src/Service/EndpointResponseNamer.php
  src/Service/EntityMetadata.php
  src/Service/SerializerFactory.php
  src/Service/SwaggerDocBuilder.php
  symfony.lock
Labels: Ready for Review, ready

#2297 Update Dependencies
  composer.lock
Labels: ready

#2301 show years, not urls in --year option description for ilios:import-mesh-universe command.
  src/Command/ImportMeshUniverseCommand.php
Labels: Ready for Review

#2305 make fixtures bundle available in all environments.
  config/bundles.php
Labels: ready
