Repository ilios/ilios, pull requests merged in 2018-11, with the labels that each got.

#2278 Create blocking migration command
  src/Command/LockingMigrationCommand.php
  src/Service/IliosFileSystem.php
  tests/Service/IliosFileSystemTest.php
Labels: Ready for Review

#2285 Update Dependencies
  composer.lock
Labels: ready

#2284 Add error capture configuration
  src/Controller/IndexController.php
  src/Service/Config.php
  templates/index/webindex.html.twig
  tests/Controller/IndexControllerTest.php
  tests/Service/ConfigTest.php
Labels: Ready for Review, ready

#2288 added docs for enabling sentry.io error-capturing
  docs/error_reporting.md
Labels: ready
