Repository ilios/ilios, pull requests merged in 2018-07, with the labels that each got.

#2188 Update Dependencies
  composer.lock
Labels: in progress

#2190 consolidate program objectives in CI report output
  src/Ilios/CoreBundle/Entity/Manager/CurriculumInventoryReportManager.php
  src/Ilios/CoreBundle/Entity/Repository/CurriculumInventoryReportRepository.php
  src/Ilios/CoreBundle/Service/CurriculumInventory/Export/Aggregator.php
  tests/CoreBundle/Entity/Manager/CurriculumInventoryReportManagerTest.php
  tests/CoreBundle/Service/CurriculumInventory/Export/AggregatorTest.php
Labels: Ready for Review

#2193 d/l action for program year objectives mapping.
  app/config/config.yml
  src/Ilios/ApiBundle/Controller/ProgramYearController.php
  src/Ilios/ApiBundle/Resources/config/special-routes.yml
  src/Ilios/CoreBundle/Entity/Manager/ProgramYearManager.php
  src/Ilios/CoreBundle/Entity/Repository/ProgramYearRepository.php
  src/Ilios/CoreBundle/Resources/config/services.yml
  tests/CoreBundle/DataLoader/CourseData.php
  tests/IliosApiBundle/Endpoints/ProgramYearTest.php
Labels: Ready for Review, in progress

#2195 explicitly set default sort order on entity relationships.
  src/Ilios/CoreBundle/Entity/AamcMethod.php
  src/Ilios/CoreBundle/Entity/AamcPcrs.php
  src/Ilios/CoreBundle/Entity/AamcResourceType.php
  src/Ilios/CoreBundle/Entity/Alert.php
  src/Ilios/CoreBundle/Entity/AlertChangeType.php
  src/Ilios/CoreBundle/Entity/AssessmentOption.php
  src/Ilios/CoreBundle/Entity/Cohort.php
  src/Ilios/CoreBundle/Entity/Competency.php
  src/Ilios/CoreBundle/Entity/Course.php
  src/Ilios/CoreBundle/Entity/CourseClerkshipType.php
  src/Ilios/CoreBundle/Entity/CourseLearningMaterial.php
  src/Ilios/CoreBundle/Entity/CurriculumInventoryAcademicLevel.php
  src/Ilios/CoreBundle/Entity/CurriculumInventoryReport.php
  src/Ilios/CoreBundle/Entity/CurriculumInventorySequenceBlock.php
  src/Ilios/CoreBundle/Entity/Department.php
  src/Ilios/CoreBundle/Entity/IlmSession.php
  src/Ilios/CoreBundle/Entity/InstructorGroup.php
  src/Ilios/CoreBundle/Entity/LearnerGroup.php
  src/Ilios/CoreBundle/Entity/LearningMaterial.php
  src/Ilios/CoreBundle/Entity/LearningMaterialStatus.php
  src/Ilios/CoreBundle/Entity/LearningMaterialUserRole.php
  src/Ilios/CoreBundle/Entity/MeshConcept.php
  src/Ilios/CoreBundle/Entity/MeshDescriptor.php
  src/Ilios/CoreBundle/Entity/MeshQualifier.php
  src/Ilios/CoreBundle/Entity/MeshTerm.php
  src/Ilios/CoreBundle/Entity/Objective.php
  src/Ilios/CoreBundle/Entity/Offering.php
  src/Ilios/CoreBundle/Entity/Program.php
  src/Ilios/CoreBundle/Entity/ProgramYear.php
  src/Ilios/CoreBundle/Entity/School.php
  src/Ilios/CoreBundle/Entity/Session.php
  src/Ilios/CoreBundle/Entity/SessionLearningMaterial.php
  src/Ilios/CoreBundle/Entity/SessionType.php
  src/Ilios/CoreBundle/Entity/Term.php
  src/Ilios/CoreBundle/Entity/User.php
  src/Ilios/CoreBundle/Entity/UserRole.php
Labels: Ready for Review

#2197 clone position attribute with objectives and LMs on course rollover.
  src/Ilios/CoreBundle/Service/CourseRollover.php
  tests/CoreBundle/Service/CourseRolloverTest.php
Labels: Ready for Review
