Repository ilios/ilios, pull requests merged in 2018-08, with the labels that each got.

#2191 Update Dependencies
  composer.lock
  tests/IliosApiBundle/Endpoints/CurriculumInventorySequenceTest.php
Labels: Ready for Review, in progress

#2199 Update Dependencies
  composer.lock
Labels: in progress

#2201 corrected printing of resource types.
  src/Ilios/CoreBundle/Service/CurriculumInventory/Export/XmlPrinter.php
Labels: Ready for Review, in progress

#2133 Add instructionalNotes to session
  app/Resources/DoctrineMigrations/Version20180803101835.php
  src/Ilios/ApiBundle/Controller/SchooleventController.php
  src/Ilios/ApiBundle/Controller/UsereventController.php
  src/Ilios/ApiBundle/Resources/swagger/definitions/Session.yml
  src/Ilios/AuthenticationBundle/RelationshipVoter/Session.php
  src/Ilios/CoreBundle/Classes/CalendarEvent.php
  src/Ilios/CoreBundle/Entity/DTO/SessionDTO.php
  src/Ilios/CoreBundle/Entity/Repository/SchoolRepository.php
  src/Ilios/CoreBundle/Entity/Repository/SessionRepository.php
  src/Ilios/CoreBundle/Entity/Repository/UserRepository.php
  src/Ilios/CoreBundle/Entity/Session.php
  src/Ilios/CoreBundle/Entity/SessionInterface.php
  src/Ilios/CoreBundle/Service/CourseRollover.php
  src/Ilios/CoreBundle/Traits/CalendarEventRepository.php
  tests/AuthenticationBundle/RelationshipVoter/SessionTest.php
  tests/CoreBundle/Classes/UserEventTest.php
  tests/CoreBundle/DataLoader/SessionData.php
  tests/CoreBundle/Entity/SessionTest.php
  tests/CoreBundle/Fixture/LoadSessionData.php
  tests/CoreBundle/Service/CourseRolloverTest.php
  tests/IliosApiBundle/Endpoints/SchooleventsTest.php
  tests/IliosApiBundle/Endpoints/SessionTest.php
  tests/IliosApiBundle/Endpoints/UsereventTest.php
Labels: Ready for Review, in progress

#2181 Add a link to the event to the ICS feed
  src/Ilios/WebBundle/Controller/IcsController.php
  tests/WebBundle/Controller/IcsControllerTest.php
Labels: Ready for Review, in progress

#2205 Fix code style issue
  tests/WebBundle/Controller/IcsControllerTest.php
Labels: Ready for Review, in progress

#2207 correctly calculate event duration if offerings are configured to be counted as one.
  src/Ilios/CoreBundle/Entity/Manager/CurriculumInventoryReportManager.php
  tests/CoreBundle/Entity/Manager/CurriculumInventoryReportManagerTest.php
Labels: Ready for Review

#2209 Update Dependencies
  composer.json
  composer.lock
Labels: Ready for Review, in progress

#2211 Add prerequisites to session
  app/Resources/DoctrineMigrations/Version20180823181914.php
  src/Ilios/ApiBundle/Resources/swagger/definitions/Session.yml
  src/Ilios/CoreBundle/Entity/DTO/SessionDTO.php
  src/Ilios/CoreBundle/Entity/Repository/SessionRepository.php
  src/Ilios/CoreBundle/Entity/Session.php
  src/Ilios/CoreBundle/Entity/SessionInterface.php
  tests/CoreBundle/DataLoader/SessionData.php
  tests/CoreBundle/Entity/SessionTest.php
  tests/CoreBundle/Fixture/LoadSessionData.php
  tests/IliosApiBundle/Endpoints/SessionTest.php
Labels: Ready for Review, in progress

#2212 Update Dependencies
  composer.lock
Labels: Ready for Review, in progress

#2215 Send the correct headers with PNG files
  src/AppBundle/Controller/IndexController.php
  tests/AppBundle/Controller/IndexControllerTest.php
Labels: in progress

#2214 Bump the API to v1.34
  app/config/config.yml
Labels: Ready for Review, in progress

#2213 Attempt to sign in users sooner
  src/AppBundle/Controller/IndexController.php
  src/Ilios/AuthenticationBundle/Service/AuthenticationInterface.php
  src/Ilios/AuthenticationBundle/Service/CasAuthentication.php
  src/Ilios/AuthenticationBundle/Service/FormAuthentication.php
  src/Ilios/AuthenticationBundle/Service/LdapAuthentication.php
  src/Ilios/AuthenticationBundle/Service/ShibbolethAuthentication.php
  tests/AuthenticationBundle/Service/ShibbolethAuthenticationTest.php
Labels: Ready for Review, in progress
