Repository ilios/ilios, pull requests merged in 2018-03, with the labels that each got.

#2066 New permissions system: prevent editing of finalized CI report
  src/Ilios/AuthenticationBundle/RelationshipVoter/CurriculumInventoryExport.php
  src/Ilios/AuthenticationBundle/RelationshipVoter/CurriculumInventoryReport.php
  src/Ilios/AuthenticationBundle/RelationshipVoter/CurriculumInventorySequence.php
  src/Ilios/AuthenticationBundle/RelationshipVoter/CurriculumInventorySequenceBlock.php
  tests/AuthenticationBundle/RelationshipVoter/AamcMethodTest.php
  tests/AuthenticationBundle/RelationshipVoter/AamcPcrsTest.php
  tests/AuthenticationBundle/RelationshipVoter/AamcResourceTypeTest.php
  tests/AuthenticationBundle/RelationshipVoter/AbstractBase.php
  tests/AuthenticationBundle/RelationshipVoter/ApplicationConfigTest.php
  tests/AuthenticationBundle/RelationshipVoter/AssessmentOptionTest.php
  tests/AuthenticationBundle/RelationshipVoter/AuthenticationTest.php
  tests/AuthenticationBundle/RelationshipVoter/CohortTest.php
  tests/AuthenticationBundle/RelationshipVoter/CompetencyTest.php
  tests/AuthenticationBundle/RelationshipVoter/CourseClerkshipTypeTest.php
  tests/AuthenticationBundle/RelationshipVoter/CourseLearningMaterialTest.php
  tests/AuthenticationBundle/RelationshipVoter/CourseTest.php
  tests/AuthenticationBundle/RelationshipVoter/CurriculumInventoryAcademicLevelTest.php
  tests/AuthenticationBundle/RelationshipVoter/CurriculumInventoryExportTest.php
  tests/AuthenticationBundle/RelationshipVoter/CurriculumInventoryInstitutionTest.php
  tests/AuthenticationBundle/RelationshipVoter/CurriculumInventoryReportTest.php
  tests/AuthenticationBundle/RelationshipVoter/CurriculumInventorySequenceBlockTest.php
  tests/AuthenticationBundle/RelationshipVoter/CurriculumInventorySequenceTest.php
  tests/AuthenticationBundle/RelationshipVoter/DepartmentTest.php
  tests/AuthenticationBundle/RelationshipVoter/IlmSessionTest.php
  tests/AuthenticationBundle/RelationshipVoter/IngestionExceptionTest.php
  tests/AuthenticationBundle/RelationshipVoter/InstructorGroupTest.php
  tests/AuthenticationBundle/RelationshipVoter/LearnerGroupTest.php
  tests/AuthenticationBundle/RelationshipVoter/LearningMaterialStatusTest.php
  tests/AuthenticationBundle/RelationshipVoter/LearningMaterialTest.php
  tests/AuthenticationBundle/RelationshipVoter/ObjectiveTest.php
  tests/AuthenticationBundle/RelationshipVoter/OfferingTest.php
  tests/AuthenticationBundle/RelationshipVoter/PendingUserUpdateTest.php
  tests/AuthenticationBundle/RelationshipVoter/ProgramTest.php
  tests/AuthenticationBundle/RelationshipVoter/ProgramYearStewardTest.php
  tests/AuthenticationBundle/RelationshipVoter/ProgramYearTest.php
  tests/AuthenticationBundle/RelationshipVoter/ReportTest.php
  tests/AuthenticationBundle/RelationshipVoter/SchoolConfigTest.php
  tests/AuthenticationBundle/RelationshipVoter/SchoolEventTest.php
  tests/AuthenticationBundle/RelationshipVoter/SchoolTest.php
  tests/AuthenticationBundle/RelationshipVoter/SessionDescriptionTest.php
  tests/AuthenticationBundle/RelationshipVoter/SessionLearningMaterialTest.php
  tests/AuthenticationBundle/RelationshipVoter/SessionTest.php
  tests/AuthenticationBundle/RelationshipVoter/SessionTypeTest.php
  tests/AuthenticationBundle/RelationshipVoter/TemporaryFileSystemTest.php
  tests/AuthenticationBundle/RelationshipVoter/TermTest.php
  tests/AuthenticationBundle/RelationshipVoter/UserEventTest.php
  tests/AuthenticationBundle/RelationshipVoter/UserMaterialTest.php
  tests/AuthenticationBundle/RelationshipVoter/UserTest.php
  tests/AuthenticationBundle/RelationshipVoter/VocabularyTest.php
Labels: Ready for Review, in progress

#2062 Dial in default permissions matrix
  src/Ilios/AuthenticationBundle/Service/DefaultPermissionMatrix.php
  tests/AuthenticationBundle/Service/DefaultPermissionMatrixTest.php
Labels: Ready for Review, in progress

#2069 Update Dependencies
  .travis.yml
  composer.lock
Labels: in progress

#2073 MeSH 2018
  app/Resources/DoctrineMigrations/Version20180307174249.php
  src/Ilios/CliBundle/Command/ImportMeshUniverseCommand.php
  src/Ilios/CoreBundle/Entity/MeshTree.php
  tests/CliBundle/Command/ImportMeshUniverseCommandTest.php
Labels: Ready for Review, in progress

#2076 Add the correct header for SVGs
  src/Ilios/WebBundle/Controller/IndexController.php
Labels: in progress

#2081 corrected parameter type declaration.
  src/Ilios/CoreBundle/Entity/Repository/MeshDescriptorRepository.php
Labels: Ready for Review

#2083 migration for activating all vocabs and competencies.
  app/Resources/DoctrineMigrations/Version20180309225012.php
Labels: DO NOT MERGE, Ready for Review, in progress

#2084 Clear and warmup the cache in our docker build
  Dockerfile
Labels: in progress

#2086 inject logger directly into controller action.
  src/Ilios/WebBundle/Controller/ErrorController.php
Labels: in progress

#2087 Update Dependencies
  composer.lock
Labels: Ready for Review, in progress

#2088 Drop support for PHP 7.1
  .travis.yml
  composer.json
  composer.lock
  docs/ilios_php_version_policy.md
  docs/install.md
Labels: Ready for Review, in progress

#2092 Apply my courses filter to administered courses
  src/Ilios/CoreBundle/Entity/Repository/CourseRepository.php
  tests/CoreBundle/DataLoader/CourseData.php
  tests/CoreBundle/DataLoader/InstructorGroupData.php
  tests/CoreBundle/DataLoader/UserData.php
  tests/IliosApiBundle/AbstractEndpointTest.php
  tests/IliosApiBundle/EndpointTestsTrait.php
  tests/IliosApiBundle/Endpoints/CourseTest.php
  tests/IliosApiBundle/Endpoints/OfferingTest.php
  tests/IliosApiBundle/Endpoints/UserTest.php
Labels: Ready for Review, in progress

#2093 fixes performance issue with "my courses"
  src/Ilios/AuthenticationBundle/Classes/SessionUser.php
  src/Ilios/AuthenticationBundle/Voter/CourseVoter.php
  src/Ilios/CoreBundle/Entity/Repository/CourseRepository.php
Labels: in progress

#2100 Add offering site to teaching reminder template
  src/Ilios/CoreBundle/Resources/views/Email/teachingreminder.text.twig
  tests/CliBundle/Command/SendTeachingRemindersCommandTest.php
Labels: Ready for Review, in progress

#2099 When syncing a user remove pending updates
  src/Ilios/CliBundle/Command/SyncUserCommand.php
  tests/CliBundle/Command/SyncUserCommandTest.php
Labels: Ready for Review, in progress

#2094 Update Dependencies
  composer.lock
Labels: Ready for Review, in progress

#2096 Convert audit_log objectId to be a varchar instead of an integer
  app/Resources/DoctrineMigrations/Version20180326223500.php
  src/Ilios/CoreBundle/Entity/AuditLog.php
  src/Ilios/CoreBundle/Entity/AuditLogInterface.php
  tests/CoreBundle/Entity/AuditLogTest.php
Labels: Ready for Review, in progress

#2102 Add School Config Commands
  src/Ilios/CliBundle/Command/ListConfigValuesCommand.php
  src/Ilios/CliBundle/Command/ListSchoolConfigValuesCommand.php
  src/Ilios/CliBundle/Command/SetConfigValueCommand.php
  src/Ilios/CliBundle/Command/SetSchoolConfigValueCommand.php
  src/Ilios/CoreBundle/Entity/Manager/SchoolConfigManager.php
  src/Ilios/CoreBundle/Entity/Repository/SchoolConfigRepository.php
  src/Ilios/CoreBundle/Resources/config/services.yml
  src/Ilios/CoreBundle/Resources/config/virtual-managers.yml
  tests/CliBundle/Command/ListSchoolConfigValuesCommandTest.php
  tests/CliBundle/Command/SetSchoolConfigValueCommandTest.php
Labels: in progress
