Repository ilios/ilios, pull requests merged in 2018-05, with the labels that each got.

#2135 tweaks to perms migration
  app/Resources/DoctrineMigrations/Version20180313211111.php
Labels: Ready for Review, in progress

#2139 Remove createCIReportInAnySchool from JWT
  src/Ilios/AuthenticationBundle/Service/JsonWebTokenManager.php
  tests/AuthenticationBundle/Service/JsonWebTokenManagerTest.php
Labels: in progress

#2141 grants update permissions on instructor groups to school- and program-directors
  src/Ilios/AuthenticationBundle/Service/DefaultPermissionMatrix.php
  tests/AuthenticationBundle/Service/DefaultPermissionMatrixTest.php
Labels: Ready for Review, in progress

#2143 build permission matrices on demand.
  src/Ilios/AuthenticationBundle/Service/DefaultPermissionMatrix.php
Labels: Ready for Review

#2146 consider program directors when checking for roles in school.
  src/Ilios/AuthenticationBundle/Classes/SessionUser.php
  src/Ilios/AuthenticationBundle/Classes/SessionUserInterface.php
Labels: Ready for Review, in progress

#2098 updated Ilios version in install docs to match most up-to-date ilios version
  docs/install.md
Labels: Ready for Review

#2150 broke up query into two, to get rid of non-standard UNION construct.
  src/Ilios/CoreBundle/Entity/Repository/CurriculumInventoryReportRepository.php
Labels: Ready for Review, in progress

#2151 add vocabulary terms linked to sessions as keywords to CI report.
  src/Ilios/CoreBundle/Entity/Repository/CurriculumInventoryReportRepository.php
  src/Ilios/CoreBundle/Service/CurriculumInventory/Exporter.php
Labels: Ready for Review, in progress

#2154 Add health checks
  app/AppKernel.php
  app/config/config.yml
  app/config/routing.yml
  composer.json
  composer.lock
Labels: Ready for Review, in progress

#2156 check instructor group membership when determining non-learner function status
  src/Ilios/AuthenticationBundle/Classes/SessionUser.php
  src/Ilios/CoreBundle/Entity/Manager/UserManager.php
  src/Ilios/CoreBundle/Entity/Repository/UserRepository.php
Labels: Ready for Review, in progress

#2159 Update Dependencies
  composer.lock
Labels: Ready for Review

#2158 replaces raw SQL with DQL equivalents
  src/Ilios/CoreBundle/Entity/Course.php
  src/Ilios/CoreBundle/Entity/CourseInterface.php
  src/Ilios/CoreBundle/Entity/Repository/CurriculumInventoryReportRepository.php
  src/Ilios/CoreBundle/Service/CurriculumInventory/Exporter.php
  tests/CoreBundle/Entity/CourseTest.php
Labels: Ready for Review

#2161 link excluded sessions to CI sequence blocks.
  app/Resources/DoctrineMigrations/Version20180514214501.php
  src/Ilios/AuthenticationBundle/Classes/SessionUser.php
  src/Ilios/CoreBundle/Entity/CurriculumInventorySequenceBlock.php
  src/Ilios/CoreBundle/Entity/CurriculumInventorySequenceBlockInterface.php
  src/Ilios/CoreBundle/Entity/DTO/CurriculumInventorySequenceBlockDTO.php
  src/Ilios/CoreBundle/Entity/Repository/CurriculumInventorySequenceBlockRepository.php
  src/Ilios/CoreBundle/Entity/Session.php
  src/Ilios/CoreBundle/Entity/SessionInterface.php
  tests/CoreBundle/DataLoader/CurriculumInventorySequenceBlockData.php
  tests/CoreBundle/Entity/CurriculumInventorySequenceBlockTest.php
  tests/CoreBundle/Entity/SessionTest.php
  tests/CoreBundle/Fixture/LoadCurriculumInventorySequenceBlockData.php
  tests/IliosApiBundle/Endpoints/CurriculumInventorySequenceBlockTest.php
Labels: Ready for Review, in progress

#2165 correct reporting on events based on ilm sessions with offerings
  src/Ilios/CoreBundle/Entity/Repository/CurriculumInventoryReportRepository.php
Labels: Ready for Review, in progress

#2166 ignore excluded sessions in report
  src/Ilios/CoreBundle/Entity/Manager/CurriculumInventoryReportManager.php
  src/Ilios/CoreBundle/Entity/Repository/CurriculumInventoryReportRepository.php
  src/Ilios/CoreBundle/Service/CurriculumInventory/Exporter.php
Labels: Ready for Review
