Repository ilios/ilios, pull requests merged in 2019-09, with the labels that each got.

#2629 Update Dependencies
  composer.lock
Labels: Ready for Review, dependencies

#2641 Improve indexing of email address
  src/Service/Index.php
  src/Service/Search.php
Labels: Ready for Review

#2640 Index everything using the messenger bus
  config/packages/messenger.yaml
  src/Command/PopulateIndexCommand.php
  src/Entity/DTO/UserDTO.php
  src/EventListener/IndexEntityChanges.php
  src/Message/CourseIndexRequest.php
  src/Message/MeshDescriptorIndexRequest.php
  src/Message/UserIndexRequest.php
  src/MessageHandler/MeshDescriptorIndexHandler.php
  src/MessageHandler/UserIndexHandler.php
  tests/Command/PopulateIndexCommandTest.php
Labels: Ready for Review

#2644 Update Dependencies
  composer.lock
Labels: Ready for Review

#2645 Improve user indexing
  src/EventListener/IndexEntityChanges.php
  src/Service/Index.php
  src/Service/Search.php
Labels: Ready for Review

#2646 Ignore Prerequisites in ICS feed
  src/Controller/IcsController.php
  tests/Controller/IcsControllerTest.php
  tests/DataLoader/SessionData.php
  tests/Endpoints/SchooleventsTest.php
  tests/Endpoints/UsereventTest.php
  tests/Fixture/LoadSessionData.php
Labels: Ready for Review

#2651 sort data by markup-free objective title.
  src/Service/CurriculumInventory/VerificationPreviewBuilder.php
  tests/Service/CurriculumInventory/VerificationPreviewBuilderTest.php
Labels: Enhancement, Ready for Review

#2652 indicate existence of lm's and pre-requisites in event description as applicable.
  src/Controller/IcsController.php
  tests/Controller/IcsControllerTest.php
Labels: Ready for Review

#2653 Fix return tags on search
  src/Service/Search.php
Labels: Ready for Review

#2662 better spacing in method names.
  src/Service/CurriculumInventory/VerificationPreviewBuilder.php
  tests/Service/CurriculumInventory/VerificationPreviewBuilderTest.php
Labels: Ready for Review

#2657 Create a config option to disable learning materials
  src/Controller/DownloadController.php
  src/Service/Config.php
  tests/Controller/DownloadControllerTest.php
  tests/Fixture/LoadApplicationConfigData.php
Labels: Ready for Review

#2661 Disable auto_setup for messenger
  config/packages/messenger.yaml
  docs/install.md
  docs/update.md
Labels: Ready for Review

#2667 Split up course indexing into chunks
  src/EventListener/IndexEntityChanges.php
Labels: Ready for Review
