Repository ilios/ilios, pull requests merged in 2019-01, with the labels that each got.

#2306 adjusted rollover test to new year.
  tests/Endpoints/CourseTest.php
Labels: Ready for Review, ready

#2307 Update Dependencies
  composer.lock
Labels: Ready for Review, ready

#2308 Update Dependencies
  composer.json
  composer.lock
Labels: Ready for Review, ready

#2292 Pre- and post-requisites in events
  src/Classes/CalendarEvent.php
  src/Classes/SchoolEvent.php
  src/Classes/UserEvent.php
  src/Controller/SchooleventController.php
  src/Controller/UsereventController.php
  src/Entity/Manager/SchoolManager.php
  src/Entity/Manager/UserManager.php
  src/Entity/Repository/SchoolRepository.php
  src/Entity/Repository/UserRepository.php
  src/Traits/CalendarEventRepository.php
  tests/Classes/SessionEventTest.php
  tests/Classes/UserEventTest.php
  tests/DataLoader/SessionData.php
  tests/Endpoints/SchooleventsTest.php
  tests/Endpoints/UsereventTest.php
Labels: Ready for Review, ready

#2309 Fix issues with pre/post requisites
  src/Entity/Repository/UserRepository.php
  tests/Endpoints/UsereventTest.php
Labels: ready

#2312 a hodgepodge of curriculum inventory export-related tweaks
  composer.json
  tests/Service/CurriculumInventory/Export/AggregatorTest.php
Labels: Ready for Review

#2319 Changes to events necessitate an API bump
  config/services.yaml
Labels: ready

#2320 When searching for users use DTOs
  src/Controller/UsersController.php
  src/Entity/Manager/UserManager.php
  src/Entity/Repository/UserRepository.php
Labels: Ready for Review, ready

#2311 consider administered courses when pulling user events.
  src/Entity/Repository/UserRepository.php
Labels: Ready for Review

#2323 Turn off error capture by default
  .env.dist
  docker-compose.yml
Labels: Ready for Review, ready
