Repository ilios/ilios, pull requests merged in 2019-11, with the labels that each got.

#2696 Update Dependencies
  composer.lock
Labels: Ready for Review, dependencies

#2704 rollover course admins.
  src/Service/CourseRollover.php
  tests/Service/CourseRolloverTest.php
Labels: Ready for Review

#2702 implements skipped tests.
  tests/Classes/SessionUserTest.php
Labels: Ready for Review

#2707 increments API version number.
  config/services.yaml
Labels: Ready for Review

#2708 Update Dependencies
  composer.lock
Labels: Ready for Review, dependencies

#2711 Update Dependencies
  composer.lock
Labels: dependencies

#2698 More accurate read-access checks to calendar events
  config/swagger/definitions/CalendarEvent.yml
  config/swagger/definitions/Schoolevent.yml
  src/Classes/CalendarEvent.php
  src/Classes/SchoolEvent.php
  src/Classes/SessionUser.php
  src/Classes/SessionUserInterface.php
  src/Controller/SchooleventController.php
  src/Controller/UsereventController.php
  src/Entity/Manager/UserManager.php
  src/Entity/Repository/SchoolRepository.php
  src/Entity/Repository/UserRepository.php
  src/RelationshipVoter/AbstractCalendarEvent.php
  src/RelationshipVoter/SchoolEvent.php
  src/RelationshipVoter/UserEvent.php
  src/Traits/CalendarEventRepository.php
  tests/Classes/SchoolEventTest.php
  tests/Classes/SessionUserTest.php
  tests/Endpoints/UsereventTest.php
  tests/RelationshipVoter/SchoolEventTest.php
  tests/RelationshipVoter/UserEventTest.php
Labels: Ready for Review
