Repository ilios/ilios, pull requests merged in 2019-12, with the labels that each got.

#2725 Update Dependencies
  composer.lock
  config/bundles.php
  src/Command/GenerateEndpointTestCommand.php
  src/Command/GenerateSwaggerApiDefinitionYamlCommand.php
  src/Entity/Manager/BaseManager.php
  src/Entity/Manager/MeshDescriptorManager.php
  src/Entity/Manager/SchoolManager.php
  src/Entity/Manager/UserManager.php
  src/Normalizer/Entity.php
  src/Service/Timestamper.php
  symfony.lock
Labels: Ready for Review, dependencies

#2730 Inject properties instead of the kernel
  src/Service/SwaggerDocBuilder.php
Labels: Ready for Review

#2733 Copy end of year date time test from course setEndDate
  tests/Service/CourseRolloverTest.php
Labels: Ready for Review

#2732 Update Dependencies
  composer.lock
Labels: dependencies

#2737 Copy start of year date time test from course setStartDate
  tests/Service/CourseRolloverTest.php
Labels: Ready for Review

#2740 consider the year previous to the new target date, not the source dat…
  tests/Service/CourseRolloverTest.php
Labels: Ready for Review

#2738 Add filter attributes to events
  config/services.yaml
  src/Classes/CalendarEvent.php
  src/Entity/Repository/SchoolRepository.php
  src/Entity/Repository/UserRepository.php
  src/Traits/CalendarEventRepository.php
  tests/Endpoints/SchooleventsTest.php
  tests/Endpoints/UsereventTest.php
Labels: Ready for Review

#2742 Update the way we handle HTTP requests
  composer.json
  composer.lock
  config/bundles.php
  config/packages/httplug.yaml
  src/Command/UpdateFrontendCommand.php
  src/Service/Fetch.php
  symfony.lock
  tests/Command/UpdateFrontendCommandTest.php
Labels: Ready for Review

#2736 Update Symfony to v4.4
  composer.json
  composer.lock
  src/Controller/ExceptionController.php
  symfony.lock
  tests/Classes/AcademicYearTest.php
  tests/Classes/LocalCachingFilesystemDecoratorTest.php
  tests/Classes/PermissionMatrixTest.php
  tests/Classes/SchoolEventTest.php
  tests/Classes/UserEventTest.php
  tests/Classes/UserMaterialTest.php
  tests/Service/MeshDescriptorSetTransmogrifierTest.php
  tests/TestCase.php
Labels: Ready for Review, dependencies

#2744 Update Dependencies
  composer.lock
Labels: Ready for Review, dependencies
