Repository ilios/ilios, pull requests merged in 2020-01, with the labels that each got.

#2748 Fix date calculate in tests
  tests/Endpoints/CourseTest.php
  tests/Service/CourseRolloverTest.php
Labels: Ready for Review

#2750 Update Dependencies
  composer.lock
Labels: Ready for Review, dependencies

#2754 Add template linting to our tests
  azure-pipelines.yml
Labels: Ready for Review

#2756 Use simplified redirect
  config/routes.yaml
Labels: Ready for Review

#2755 Remove Webserver Bundle
  .gitignore
  composer.json
  composer.lock
  config/bundles.php
  symfony.lock
Labels: Ready for Review

#2751 [BREAKING] Update Flex Recipes for Symfony 4.4
  .env
  .env.dev
  .env.test
  .gitignore
  Dockerfile
  azure-pipelines.yml
  bin/console
  bin/phpunit
  config/bootstrap.php
  config/packages/dev/doctrine.yaml
  config/packages/doctrine.yaml
  config/packages/framework.yaml
  config/packages/prod/doctrine.yaml
  config/packages/prod/framework.yaml
  config/packages/prod/routing.yaml
  config/packages/routing.yaml
  config/packages/security_checker.yaml
  config/packages/swiftmailer.yaml
  config/packages/test/twig.yaml
  config/packages/test/validator.yaml
  config/packages/twig.yaml
  config/packages/validator.yaml
  config/routes/dev/framework.yaml
  docker-compose.yml
  docs/env_vars_and_config.md
  docs/update.md
  phpunit.xml.dist
  public/.htaccess
  public/index.php
  src/Controller/ExceptionController.php
  src/Kernel.php
  src/Monitor/RequiredENV.php
  symfony.lock
  tests/Endpoints/CourseTest.php
Labels: Ready for Review

#2672 Index the contents of learning materials
  .env
  composer.json
  composer.lock
  config/packages/messenger.yaml
  config/packages/prod/monolog.yaml
  docker-compose.yml
  docker/elasticsearch-dev/Dockerfile
  src/Classes/ElasticSearchBase.php
  src/Classes/IndexableCourse.php
  src/Classes/IndexableSession.php
  src/Command/PopulateIndexCommand.php
  src/Entity/CourseLearningMaterial.php
  src/Entity/CourseLearningMaterialInterface.php
  src/Entity/DTO/LearningMaterialDTO.php
  src/Entity/Manager/LearningMaterialManager.php
  src/Entity/Repository/CourseRepository.php
  src/Entity/Repository/LearningMaterialRepository.php
  src/Entity/SessionLearningMaterial.php
  src/Entity/SessionLearningMaterialInterface.php
  src/EventListener/IndexEntityChanges.php
  src/Message/LearningMaterialIndexRequest.php
  src/MessageHandler/LearningMaterialIndexHandler.php
  src/Service/IliosFileSystem.php
  src/Service/Index.php
  src/Service/LearningMaterialDecoratorFactory.php
  src/Service/Search.php
  symfony.lock
  tests/Entity/DTO/LearningMaterialDTOTest.php
  tests/Service/IndexTest.php
Labels: Ready for Review

#2758 Clear validation deprecations
  src/Entity/Alert.php
  src/Entity/AuditLog.php
  src/Entity/Authentication.php
  src/Entity/Competency.php
  src/Entity/Course.php
  src/Entity/CourseLearningMaterial.php
  src/Entity/CurriculumInventoryAcademicLevel.php
  src/Entity/CurriculumInventoryReport.php
  src/Entity/CurriculumInventorySequence.php
  src/Entity/CurriculumInventorySequenceBlock.php
  src/Entity/IlmSession.php
  src/Entity/LearnerGroup.php
  src/Entity/LearningMaterial.php
  src/Entity/MeshConcept.php
  src/Entity/MeshDescriptor.php
  src/Entity/MeshTerm.php
  src/Entity/Offering.php
  src/Entity/Program.php
  src/Entity/Report.php
  src/Entity/School.php
  src/Entity/Session.php
  src/Entity/SessionDescription.php
  src/Entity/SessionLearningMaterial.php
  src/Entity/Term.php
  src/Entity/User.php
Labels: Code Quality, Ready for Review

#2762 Pass single attribute to authorization check
  src/Controller/CoursesController.php
  src/Controller/CurriculumInventoryReportController.php
Labels: Ready for Review

#2763 Use symfony auto migrating password hash
  config/packages/security.yaml
  src/Command/AddUserCommand.php
  src/Command/ChangePasswordCommand.php
  src/Command/InstallFirstUserCommand.php
  src/Controller/AuthenticationController.php
  src/Entity/Authentication.php
  src/Entity/AuthenticationInterface.php
  src/Form/Encoder.php
  src/Migrations/Version20200115050155.php
  src/Service/FormAuthentication.php
  tests/Command/AddUserCommandTest.php
  tests/Command/ChangePasswordCommandTest.php
  tests/Command/InstallFirstUserCommandTest.php
  tests/Controller/AuthControllerTest.php
  tests/Fixture/LoadAuthenticationData.php
  tests/Service/FormAuthenticationTest.php
Labels: Ready for Review

#2766 Update Dependencies
  composer.lock
  symfony.lock
Labels: dependencies

#2768 Refactor Indexing
  src/Classes/ElasticSearchBase.php
  src/Classes/IndexableSession.php
  src/Command/ImportMeshUniverseCommand.php
  src/Command/Index/CreateCommand.php
  src/Command/Index/DropCommand.php
  src/Command/Index/UpdateCommand.php
  src/Controller/ConfigController.php
  src/Controller/Search.php
  src/Entity/Manager/MeshDescriptorManager.php
  src/EventListener/IndexEntityChanges.php
  src/MessageHandler/CourseIndexHandler.php
  src/MessageHandler/LearningMaterialIndexHandler.php
  src/MessageHandler/MeshDescriptorIndexHandler.php
  src/MessageHandler/UserIndexHandler.php
  src/Service/Index.php
  src/Service/Index/Curriculum.php
  src/Service/Index/LearningMaterials.php
  src/Service/Index/Manager.php
  src/Service/Index/Mesh.php
  src/Service/Index/Users.php
  src/Service/Search.php
  tests/Command/ImportMeshUniverseCommandTest.php
  tests/Command/Index/CreateCommandTest.php
  tests/Command/Index/DropCommandTest.php
  tests/Controller/SearchControllerTest.php
  tests/Service/Index/CurriculumTest.php
  tests/Service/Index/MeshTest.php
  tests/Service/Index/UsersTest.php
  tests/Service/IndexTest.php
  tests/Service/SearchTest.php
Labels: Code Quality, Ready for Review

#2770 fixes password changer command for legacy accounts
  src/Command/ChangePasswordCommand.php
  tests/Command/ChangePasswordCommandTest.php
Labels: Ready for Review

#2778 Ensure setup is always run
  azure-pipelines.yml
  src/Kernel.php
  tests/Endpoints/AamcPcrsTest.php
Labels: Ready for Review

#2781 Add explicit cookie properties
  src/Controller/CurriculumInventoryDownloadController.php
Labels: Ready for Review

#2782 Correct namespace for ObjectManager
  src/DataFixtures/ORM/AbstractFixture.php
  tests/Fixture/LoadAamcMethodData.php
  tests/Fixture/LoadAamcPcrsData.php
  tests/Fixture/LoadAamcResourceTypeData.php
  tests/Fixture/LoadAlertChangeTypeData.php
  tests/Fixture/LoadAlertData.php
  tests/Fixture/LoadApplicationConfigData.php
  tests/Fixture/LoadAssessmentOptionData.php
  tests/Fixture/LoadAuditLogData.php
  tests/Fixture/LoadAuthenticationData.php
  tests/Fixture/LoadCohortData.php
  tests/Fixture/LoadCompetencyData.php
  tests/Fixture/LoadCourseClerkshipTypeData.php
  tests/Fixture/LoadCourseData.php
  tests/Fixture/LoadCourseLearningMaterialData.php
  tests/Fixture/LoadCurriculumInventoryAcademicLevelData.php
  tests/Fixture/LoadCurriculumInventoryExportData.php
  tests/Fixture/LoadCurriculumInventoryInstitutionData.php
  tests/Fixture/LoadCurriculumInventoryReportData.php
  tests/Fixture/LoadCurriculumInventorySequenceBlockData.php
  tests/Fixture/LoadCurriculumInventorySequenceData.php
  tests/Fixture/LoadDepartmentData.php
  tests/Fixture/LoadIlmSessionData.php
  tests/Fixture/LoadIngestionExceptionData.php
  tests/Fixture/LoadInstructorGroupData.php
  tests/Fixture/LoadLearnerGroupData.php
  tests/Fixture/LoadLearningMaterialData.php
  tests/Fixture/LoadLearningMaterialStatusData.php
  tests/Fixture/LoadLearningMaterialUserRoleData.php
  tests/Fixture/LoadMeshConceptData.php
  tests/Fixture/LoadMeshDescriptorData.php
  tests/Fixture/LoadMeshPreviousIndexingData.php
  tests/Fixture/LoadMeshQualifierData.php
  tests/Fixture/LoadMeshTermData.php
  tests/Fixture/LoadMeshTreeData.php
  tests/Fixture/LoadObjectiveData.php
  tests/Fixture/LoadOfferingData.php
  tests/Fixture/LoadPendingUserUpdateData.php
  tests/Fixture/LoadProgramData.php
  tests/Fixture/LoadProgramYearData.php
  tests/Fixture/LoadProgramYearStewardData.php
  tests/Fixture/LoadReportData.php
  tests/Fixture/LoadSchoolConfigData.php
  tests/Fixture/LoadSchoolData.php
  tests/Fixture/LoadSessionData.php
  tests/Fixture/LoadSessionDescriptionData.php
  tests/Fixture/LoadSessionLearningMaterialData.php
  tests/Fixture/LoadSessionTypeData.php
  tests/Fixture/LoadTermData.php
  tests/Fixture/LoadUserData.php
  tests/Fixture/LoadUserRoleData.php
  tests/Fixture/LoadVocabularyData.php
Labels: Ready for Review
