Repository ilios/ilios, pull requests merged in 2020-02, with the labels that each got.

#2786 Replace Zend with Laminas
  src/Monitor/Composer.php
  src/Monitor/Frontend.php
  src/Monitor/IliosFileSystem.php
  src/Monitor/NoDefaultSecret.php
  src/Monitor/PhpConfiguration.php
  src/Monitor/RequiredENV.php
  src/Monitor/Timezone.php
Labels: Ready for Review

#2788 Migrate to Github Actions
  .azure/install-steps-template.yaml
  .azure/phpunit-job-template.yaml
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  azure-pipelines.yml
Labels: Ready for Review

#2793 Run coverage on all tests
  .github/workflows/coverage.yml
Labels: Ready for Review

#2795 Update Dependencies
  composer.lock
Labels: Ready for Review, dependencies

#2791 Add some light caching of database configuration values
  src/Entity/Manager/ApplicationConfigManager.php
  src/Entity/Repository/ApplicationConfigRepository.php
Labels: Enhancement, Ready for Review

#2798 Remove composer cache
  .github/workflows/ci.yml
Labels: Ready for Review

#2787 Fixup some health checks
  src/Monitor/NoDefaultSecret.php
  src/Monitor/PhpConfiguration.php
Labels: Ready for Review

#2797 App config cache tweak
  .env
  .env.test
  config/services.yaml
  config/services_test.yaml
  src/Entity/Manager/ApplicationConfigManager.php
Labels: Ready for Review

#2800 fixes intermittent test failures related to time freezing.
  tests/AbstractEndpointTest.php
  tests/Endpoints/LearningMaterialTest.php
  tests/Endpoints/MeshConceptTest.php
  tests/Endpoints/MeshDescriptorTest.php
  tests/Endpoints/MeshQualifierTest.php
  tests/Endpoints/MeshTermTest.php
  tests/Endpoints/OfferingTest.php
  tests/Endpoints/ReportTest.php
  tests/Endpoints/SessionTest.php
Labels: Ready for Review

#2808 Add PHP Compatibility Code Sniffer
  composer.json
  composer.lock
  phpcs.xml.dist
  src/EventListener/LogEntityChanges.php
  src/Migrations/Version20150826130000.php
  src/Migrations/Version20150916173024.php
  src/Migrations/Version20160615223611.php
  src/Service/Directory.php
  symfony.lock
  tests/Service/IliosFileSystemTest.php
  tests/Service/NonCachingIliosFileSystemTest.php
Labels: Ready for Review

#2814 Delete when index is missing data
  src/Classes/ElasticSearchBase.php
Labels: BUG
